# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-28 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthQQUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('openid', models.CharField(max_length=64, verbose_name='openid')),
            ],
            options={
                'db_table': 'tb_oauth_qq',
            },
        ),
    ]
